### ISSUE TITLE
some sh:path are not returned by ShPropertyShape class

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/shapes-testing#3]
In TopQ_shPathFromFiles we read all shapes files and check for the path of their PropertyShape. In two instances, path returned are null: for 

https://github.com/buda-base/editor-templates/blob/master/templates/core/person.event.shapes.ttl 

and 

https://github.com/buda-base/editor-templates/blob/master/templates/core/person.ui.shapes.ttl

**Comment by xristy** [comment]
The person.ui.shapes.ttl doesn't have any sh:path because they are  intended to be imported from person.shapes.ttl

**Comment by MarcAgate** [comment]
Fixed as of commit commit 1587e13 
in https://github.com/buda-base/editor-templates
